services:
  postgres_prod:
    container_name: 'postgres-studyconnect-prod'
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:5432'
